"""Stable public exports for race presets and path helpers."""

from utils.race.race_tracks import (
    PATH_TYPE,
    PATH_TYPE_ICON,
    PATH_TYPE_TEXT,
    RACETRACKS,
    RACE_PRESET,
    RACE_SCHEDULE,
    RACE_VENUE_BY_ID,
    WEB_RACE_FINISH_DISTANCE_BY_TYPE,
    build_current_track_text,
    build_path_effect_text,
    build_track_progress_text,
    get_current_path_type,
    get_race_distance_m,
    get_race_distance_type,
    get_race_turns,
    get_race_venue,
    get_path_effect,
    get_web_race_finish_distance,
    render_path,
)

__all__ = [
    "PATH_TYPE",
    "PATH_TYPE_ICON",
    "PATH_TYPE_TEXT",
    "RACETRACKS",
    "RACE_PRESET",
    "RACE_SCHEDULE",
    "RACE_VENUE_BY_ID",
    "WEB_RACE_FINISH_DISTANCE_BY_TYPE",
    "build_current_track_text",
    "build_path_effect_text",
    "build_track_progress_text",
    "get_current_path_type",
    "get_race_distance_m",
    "get_race_distance_type",
    "get_race_turns",
    "get_race_venue",
    "get_path_effect",
    "get_web_race_finish_distance",
    "render_path",
]
