"""Acceleration Skills catalog."""

ACCELERATION_SKILLS = {
    "acc_001": {
        "name": "Encroaching Shadow",
        "icon": "Acceleration_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {"style": "End", "lastspurt": True, "path_type": 1},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "modify_current_speed", "value": 2},
            {"type": "add_dkh", "value": 1, "duration": "this_roll"},
        ],
        "tags": ["straight", "lastspurt", "end", "acceleration"],
    },
    "acc_002": {
        "name": "Determined Descent",
        "icon": "Acceleration_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {"style": "Pace", "path_type": 4},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "modify_current_speed", "value": 1.5},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 40,
                "duration": "this_roll",
            },
        ],
        "tags": ["pace", "downhill", "acceleration"],
    },
    "acc_003": {
        "name": "On Your Left!",
        "icon": "Acceleration_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {"style": "Late", "phase_min": 3, "phase_max": 4},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "modify_current_speed", "value": 2},
            {"type": "add_dkh", "value": 1, "duration": "this_roll"},
        ],
        "tags": ["late", "acceleration", "late_race"],
    },
    "acc_004": {
        "name": "Turbo Sprint",
        "icon": "Acceleration_rare",
        "cooldown": 8,
        "cost": 50,
        "trigger": {"path_type": 1, "distance_type": "Sprint"},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "add_dkh", "value": 3, "duration": "this_roll"}],
        "tags": ["sprint", "straight", "acceleration"],
    },
    "acc_005": {
        "name": "Groundwork",
        "icon": "Acceleration_rare",
        "cooldown": 10,
        "cost": 40,
        "trigger": {"phase_min": 1, "phase_max": 1},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "modify_current_speed", "value": 1}],
        "tags": ["start", "acceleration"],
    },
    "acc_006": {
        "name": "No Stopping Me!",
        "icon": "Acceleration_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {"lastspurt": True, "front_blocked": True},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "modify_current_speed", "value": 2},
            {"type": "cap_floor", "value": 5, "duration": "this_roll"},
        ],
        "tags": ["lastspurt", "blocked", "acceleration"],
    },
    "acc_007": {
        "name": "Neck and Neck",
        "icon": "Acceleration_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {"style": "Pace", "phase_min": 3, "phase_max": 4},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "modify_current_speed", "value": 1},
            {"type": "add_dkh", "value": 2},
        ],
        "tags": ["pace", "late_race", "acceleration", "burst"],
    },
    "acc_008": {
        "name": "Runaway",
        "icon": "Acceleration_rare",
        "cooldown": 10,
        "cost": 50,
        "trigger": {"style": "Front", "turn_min": 1, "turn_max": 1},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "modify_current_speed", "value": 2},
            {"type": "reduce_stamina", "value": 1},
        ],
        "tags": ["front", "start", "acceleration", "stamina_cost"],
    },
    "acc_009": {
        "name": "Unrestrained",
        "icon": "Acceleration_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {"style": "Front", "phase_min": 4, "phase_max": 4, "path_type": 2},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "add_dkh", "value": 3, "duration": "this_roll"}],
        "tags": ["front", "final_corner", "acceleration", "burst"],
    },
    "acc_010": {
        "name": "Radiant Star",
        "icon": "Acceleration_rare",
        "cooldown": 6,
        "cost": 120,
        "trigger": {"phase_min": 3, "phase_max": 4},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "modify_current_speed", "value": 1},
            {"type": "cap_floor", "value": 6, "duration": "this_roll"},
            {"type": "add_dkh", "value": 2, "duration": "this_roll"},
            {"type": "recover_stamina", "value": 1},
        ],
        "tags": ["mid_late", "acceleration", "sustain"],
    },
}
