"""Debuff Skills catalog."""

DEBUFF_SKILLS = {
    "debuff_001": {
        "name": "Battle Formation",
        "icon": "DecreaseVelocity_rare",
        "cooldown": 10,
        "cost": 50,
        "trigger": {
            "phase_min": 1,
            "phase_max": 2,
            "distance_type": "Mile",
            "position_group": "back",
            "target_distance_min": 1,
            "target_distance_max": 999,
        },
        "target": {"scope": "all_front", "limit": 20},
        "effects": [{"type": "modify_roll_cap", "value": -5, "duration": "this_roll"}],
        "tags": ["debuff", "mile", "early_race"],
    },
    "debuff_002": {
        "name": "Stamina Siphon",
        "icon": "ReduceSTA_rare",
        "cooldown": 10,
        "cost": 60,
        "trigger": {
            "phase_min": 2,
            "phase_max": 3,
            "position_group": "back",
            "distance_type": "Long",
            "target_distance_min": 1,
            "target_distance_max": 999,
        },
        "target": {"scope": "nearest_front", "limit": 20},
        "effects": [
            {"type": "reduce_stamina", "value": 0.5},
            {"type": "self_heal_stamina", "value": 1},
        ],
        "tags": ["debuff", "long", "stamina"],
    },
    "debuff_003": {
        "name": "Dominator",
        "icon": "DecreaseVelocity_rare",
        "cooldown": 10,
        "cost": 50,
        "trigger": {
            "phase_min": 4,
            "phase_max": 4,
            "position_group": "back",
            "distance_type": "Medium",
            "target_distance_min": 1,
            "target_distance_max": 999,
        },
        "target": {"scope": "all_front", "limit": 20},
        "effects": [{"type": "modify_roll_cap", "value": -5, "duration": "this_roll"}],
        "tags": ["debuff", "medium", "late_race"],
    },
    "debuff_004": {
        "name": "Dazzling Disorientation",
        "icon": "Blind_rare",
        "cooldown": 10,
        "cost": 50,
        "trigger": {
            "style": "Pace",
            "phase_min": 4,
            "phase_max": 4,
            "position_group": "front",
            "target_distance_min": -150,
            "target_distance_max": 150,
        },
        "target": {"scope": "all_back", "limit": 20},
        "effects": [
            {"type": "modify_enemy_gold_range", "value": -15, "duration": "next_turn"},
            {
                "type": "modify_enemy_gold_lane_range",
                "value": -1,
                "duration": "next_turn",
            },
        ],
        "tags": ["blind", "pace", "debuff", "lead"],
    },
    "debuff_005": {
        "name": "Illusionist",
        "icon": "Blind_rare",
        "cooldown": 10,
        "cost": 50,
        "trigger": {
            "phase_min": 4,
            "phase_max": 4,
            "distance_type": "Long",
            "target_distance_min": 1,
            "target_distance_max": 300,
        },
        "target": {"scope": "all_front", "limit": 20},
        "effects": [
            {"type": "modify_enemy_gold_range", "value": -12, "duration": "next_turn"},
            {
                "type": "modify_enemy_gold_lane_range",
                "value": -1,
                "duration": "next_turn",
            },
        ],
        "tags": ["blind", "long", "debuff"],
    },
    "debuff_006": {
        "name": "All-Seeing Eyes",
        "icon": "ReduceSTA_rare",
        "cooldown": 10,
        "cost": 50,
        "trigger": {
            "style": "Late",
            "phase_min": 3,
            "phase_max": 4,
            "target_distance_min": 1,
            "target_distance_max": 999,
        },
        "target": {"scope": "all_front", "limit": 20},
        "effects": [{"type": "reduce_stamina", "value": 0.75}],
        "tags": ["late", "debuff", "stamina", "all_front"],
    },
    "debuff_007": {
        "name": "Tantalizing Trick",
        "icon": "ReduceSTA_rare",
        "cooldown": 8,
        "cost": 40,
        "trigger": {"target_distance_min": 0, "target_distance_max": -30},
        "target": {"scope": "all_back", "limit": 1},
        "effects": [
            {"type": "reduce_stamina", "value": 1},
            {"type": "force_rush", "value": 1},
        ],
        "tags": ["debuff", "mindgame"],
    },
    "debuff_008": {
        "name": "Tether",
        "icon": "DecreaseVelocity",
        "cooldown": 10,
        "cost": 60,
        "trigger": {
            "distance_type": "Medium",
            "phase_min": 3,
            "phase_max": 4,
            "position_group": "back",
            "target_distance_min": 1,
            "target_distance_max": 150,
        },
        "target": {"scope": "all_front", "limit": 20, "same_lane_only": False},
        "effects": [{"type": "modify_roll_cap", "value": -3, "duration": "this_roll"}],
        "tags": ["medium", "late_race", "back", "debuff", "velocity"],
    },
    "debuff_009": {
        "name": "Adored by All",
        "icon": "DecreaseVelocity_rare",
        "cooldown": 10,
        "cost": 80,
        "trigger": {
            "distance_type": "Sprint",
            "phase_min": 1,
            "phase_max": 1,
            "position_group": "front",
            "target_distance_min": -150,
            "target_distance_max": -1,
        },
        "target": {"scope": "all_back", "limit": 20, "same_lane_only": False},
        "effects": [{"type": "modify_roll_cap", "value": -5, "duration": "this_roll"}],
        "tags": ["sprint", "early_race", "front", "debuff", "velocity", "rare"],
    },
    "debuff_010": {
        "name": "Intimidate",
        "icon": "DecreaseVelocity",
        "cooldown": 10,
        "cost": 60,
        "trigger": {
            "distance_type": "Sprint",
            "phase_min": 1,
            "phase_max": 1,
            "position_group": "front",
            "target_distance_min": -150,
            "target_distance_max": -1,
        },
        "target": {"scope": "all_back", "limit": 3, "same_lane_only": False},
        "effects": [{"type": "modify_roll_cap", "value": -3, "duration": "this_roll"}],
        "tags": ["sprint", "early_race", "front", "debuff", "velocity"],
    },
    "debuff_011": {
        "name": "Stamina Eater",
        "icon": "ReduceSTA",
        "cooldown": 10,
        "cost": 60,
        "trigger": {
            "phase_min": 2,
            "phase_max": 3,
            "position_group": "back",
            "distance_type": "Long",
            "target_distance_min": 1,
            "target_distance_max": 999,
        },
        "target": {"scope": "nearest_front", "limit": 20},
        "effects": [
            {"type": "reduce_stamina", "value": 0.3},
            {"type": "self_heal_stamina", "value": 0.75},
        ],
        "tags": ["debuff", "long", "stamina"],
    },
    "debuff_012": {
        "name": "Speed Eater",
        "icon": "DecreaseVelocity",
        "cooldown": 10,
        "cost": 60,
        "trigger": {
            "distance_type": "Mile",
            "phase_min": 2,
            "phase_max": 3,
            "position_group": "front",
            "target_distance_min": -150,
            "target_distance_max": -1,
        },
        "target": {"scope": "all_back", "limit": 20, "same_lane_only": False},
        "effects": [{"type": "modify_velocity", "value": -3, "duration": "this_roll"}],
        "tags": ["mile", "mid_race", "front", "debuff", "velocity"],
    },
}
