"""Recovery Skills catalog."""

RECOVERY_SKILLS = {
    "rec_001": {
        "name": "Swinging Maestro",
        "icon": "Recovery_rare",
        "cooldown": 8,
        "cost": 50,
        "trigger": {"path_type": 2},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "recover_stamina", "value": 2}],
        "tags": ["corner", "recovery"],
    },
    "rec_002": {
        "name": "Go-Home Specialist",
        "icon": "Recovery_rare",
        "cooldown": 8,
        "cost": 40,
        "trigger": {"path_type": 4, "style": "End"},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "recover_stamina", "value": 2}],
        "tags": ["downhill", "recovery", "end"],
    },
    "rec_003": {
        "name": "Keen Eye",
        "icon": "Recovery_rare",
        "cooldown": 10,
        "cost": 60,
        "trigger": {
            "style": "Pace",
            "phase_min": 2,
            "phase_max": 3,
            "target_distance_min": 1,
            "target_distance_max": 150,
        },
        "target": {"scope": "all_front", "limit": 12},
        "effects": [
            {"type": "recover_stamina", "value": 1.5},
            {"type": "modify_roll_cap", "value": -3, "duration": "this_roll"},
        ],
        "tags": ["recovery", "debuff", "front_target"],
    },
    "rec_004": {
        "name": "Calm and Collected",
        "icon": "Recovery_rare",
        "cooldown": 8,
        "cost": 40,
        "trigger": {"style": "Pace", "phase_min": 2, "phase_max": 2},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "recover_stamina", "value": 2}],
        "tags": ["pace", "recovery", "mid_race"],
    },
    "rec_005": {
        "name": "Breath of Fresh Air",
        "icon": "Recovery_rare",
        "cooldown": 8,
        "cost": 50,
        "trigger": {"path_type": 1},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "recover_stamina", "value": 2}],
        "tags": ["straight", "recovery"],
    },
    "rec_006": {
        "name": "Cooldown",
        "icon": "Recovery_rare",
        "cooldown": 8,
        "cost": 40,
        "trigger": {"path_type": 1, "distance_type": "Long"},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "recover_stamina", "value": 2}],
        "tags": ["long", "straight", "recovery"],
    },
    "rec_007": {
        "name": "Trackblazer",
        "icon": "Recovery_rare",
        "cooldown": 8,
        "cost": 40,
        "trigger": {
            "phase_min": 2,
            "phase_max": 3,
            "position_group": "front",
            "distance_type": "Medium",
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "recover_stamina", "value": 2}],
        "tags": ["medium", "lead", "recovery"],
    },
    "rec_008": {
        "name": "Restless",
        "icon": "Recovery_rare",
        "cooldown": 8,
        "cost": 40,
        "trigger": {"style": "Front", "path_type": 3},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "recover_stamina", "value": 2}],
        "tags": ["front", "uphill", "recovery"],
    },
    "rec_009": {
        "name": "Relax",
        "icon": "Recovery_rare",
        "cooldown": 8,
        "cost": 40,
        "trigger": {"style": "Late", "phase_min": 4, "phase_max": 4},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "recover_stamina", "value": 2}],
        "tags": ["late", "recovery", "late_race"],
    },
    "rec_010": {
        "name": "Corner Recovery",
        "icon": "stamina",
        "cooldown": 8,
        "cost": 50,
        "trigger": {"path_type": 2},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "recover_stamina", "value": 1.5}],
        "tags": ["corner", "recovery"],
    },
    "rec_011": {
        "name": "Straightaway Recovery",
        "icon": "stamina",
        "cooldown": 8,
        "cost": 50,
        "trigger": {"path_type": 1},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "recover_stamina", "value": 1.5}],
        "tags": ["straight", "recovery"],
    },
    "rec_012": {
        "name": "Gourmand",
        "icon": "Recovery_rare",
        "cooldown": 8,
        "cost": 40,
        "trigger": {"style": "Pace", "phase_min": 2, "phase_max": 3},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "recover_stamina", "value": 2}],
        "tags": ["pace", "mid_race", "recovery", "rare"],
    },
    "rec_013": {
        "name": "Hydrate",
        "icon": "stamina",
        "cooldown": 8,
        "cost": 40,
        "trigger": {"style": "Pace", "phase_min": 2, "phase_max": 3},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "recover_stamina", "value": 1.5}],
        "tags": ["pace", "mid_race", "recovery"],
    },
    "rec_014": {
        "name": "After-School Stroll",
        "icon": "stamina",
        "cooldown": 8,
        "cost": 40,
        "trigger": {"style": "End", "path_type": 4},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "recover_stamina", "value": 1.5}],
        "tags": ["end", "downhill", "recovery"],
    },
    "rec_015": {
        "name": "Moxie",
        "icon": "stamina",
        "cooldown": 8,
        "cost": 40,
        "trigger": {"style": "Front", "path_type": 3},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "recover_stamina", "value": 1}],
        "tags": ["front", "uphill", "recovery"],
    },
}
