"""Unique Skills catalog."""

UNIQUE_SKILLS = {
    "unique_001": {
        "name": "Let's Pump Some Iron",
        "icon": "UniqueAcceleration",
        "cooldown": 8,
        "cost": 120,
        "trigger": {"last_corner": True, "position_group": "back"},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "modify_current_speed", "value": 2},
            {"type": "cap_floor", "value": 9, "duration": "this_roll"},
        ],
        "tags": ["corner", "late_race", "acceleration", "unique"],
    },
    "unique_002": {
        "name": "Red Shift/LP1211-M",
        "icon": "UniqueAcceleration",
        "cooldown": 8,
        "cost": 120,
        "trigger": {"phase_min": 4, "phase_max": 4, "position_group": "front"},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "add_dkh", "value": 2, "duration": "this_roll"},
            {"type": "cap_floor", "value": 9, "duration": "this_roll"},
        ],
        "tags": ["corner", "late_race", "lead", "acceleration", "unique"],
    },
    "unique_003": {
        "name": "Triumphant Pulse",
        "icon": "UniqueVelocity",
        "cooldown": 8,
        "cost": 120,
        "trigger": {
            "phase_min": 4,
            "phase_max": 4,
            "position_group": "front",
            "target_distance_min": 0,
            "target_distance_max": 200,
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "cap_floor", "value": 15, "duration": "this_roll"}],
        "tags": ["late_race", "lead", "velocity", "positioning", "unique"],
    },
    "unique_004": {
        "name": "Moving Past, and Beyond",
        "icon": "UniqueAcceleration",
        "cooldown": 8,
        "cost": 120,
        "trigger": {"phase_min": 3, "phase_max": 4, "position_group": "middle"},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "add_dkh", "value": 3, "duration": "this_roll"},
            {"type": "modify_current_speed", "value": 2},
        ],
        "tags": ["mid_race", "late_race", "acceleration", "unique"],
    },
    "unique_005": {
        "name": "Angling and Scheming",
        "icon": "UniqueAcceleration",
        "cooldown": 8,
        "cost": 120,
        "trigger": {"last_corner": True, "position_group": "front"},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "add_dkh", "value": 3, "duration": "this_roll"},
            {"type": "cap_floor", "value": 6, "duration": "this_roll"},
        ],
        "tags": ["corner", "late_race", "lead", "acceleration", "unique"],
    },
    "unique_006": {
        "name": "Cacao Operation Cacao",
        "icon": "UniqueVelocity",
        "cooldown": 8,
        "cost": 120,
        "trigger": {
            "phase_min": 2,
            "phase_max": 3,
            "position_group": "front",
            "path_type": 2,
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 40,
                "duration": "this_roll",
            },
            {"type": "cap_floor", "value": 6, "duration": "this_roll"},
            {"type": "recover_stamina", "value": 1},
        ],
        "tags": ["corner", "mid_race", "lead", "velocity", "recovery", "unique"],
    },
    "unique_007": {
        "name": "U=ma2",
        "icon": "UniqueAcceleration",
        "cooldown": 8,
        "cost": 100,
        "trigger": {
            "phase_min": 3,
            "phase_max": 4,
            "position_group": "middle",
            "path_type": 2,
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 6, "duration": "this_roll"},
            {"type": "recover_stamina", "value": 3},
        ],
        "tags": ["corner", "late_race", "middle", "acceleration", "recovery", "unique"],
    },
    "unique_008": {
        "name": "Budding Blossom",
        "icon": "UniqueAcceleration",
        "cooldown": 8,
        "cost": 120,
        "trigger": {
            "last_corner": True,
            "phase_min": 3,
            "phase_max": 4,
            "position_group": "middle",
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 12, "duration": "this_roll"},
            {"type": "modify_current_speed", "value": 1},
        ],
        "tags": ["corner", "late_race", "middle", "acceleration", "recovery", "unique"],
    },
    "unique_009": {
        "name": "Every Rose Has Its Fangs",
        "icon": "UniqueVelocity",
        "cooldown": 8,
        "cost": 120,
        "trigger": {
            "phase_min": 2,
            "phase_max": 2,
            "position_group": "middle",
            "target_distance_min": 1,
            "target_distance_max": 999,
        },
        "target": {"scope": "all_front", "limit": 20, "same_lane_only": False},
        "effects": [
            {"type": "reduce_stamina", "value": 0.3},
            {"type": "self_heal_stamina", "value": 0.5},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 50,
                "duration": "this_roll",
                "target": {"scope": "self", "limit": 1},
            },
        ],
        "tags": ["middle", "mid_race", "velocity", "recovery", "debuff", "unique"],
    },
    "unique_010": {
        "name": "564 Escapades",
        "icon": "UniqueVelocity",
        "cooldown": 10,
        "cost": 120,
        "trigger": {"phase_min": 3, "phase_max": 4},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 40,
                "duration": "this_roll",
            },
            {"type": "activate_random_equipped_skills", "count": 1, "max_cost": 80},
        ],
        "tags": ["late_race", "velocity", "unique"],
    },
    "unique_011": {
        "name": "Blossoming World",
        "icon": "UniqueVelocity",
        "cooldown": 8,
        "cost": 120,
        "trigger": {"phase_min": 3, "phase_max": 3, "position_group": "middle"},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 40,
                "duration": "this_roll",
            },
            {"type": "cap_floor", "value": 9, "duration": "this_roll"},
            {
                "type": "recover_stamina",
                "value": 0.75,
                "condition": {"distance_type": "Long"},
            },
        ],
        "tags": ["middle", "mid_race", "velocity", "recovery", "long", "unique"],
    },
    "unique_012": {
        "name": "Ad Astra",
        "icon": "UniqueVelocity",
        "cooldown": 8,
        "cost": 100,
        "trigger": {"phase_min": 3, "phase_max": 3, "position_group": "middle"},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 12, "duration": "this_roll"},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 50,
                "duration": "this_roll",
                "condition": {"skill_use_count_min": 4},
            },
        ],
        "tags": ["middle", "mid_race", "velocity", "unique"],
    },
}
