"""Velocity Skills catalog."""

VELOCITY_SKILLS = {
    "vel_001": {
        "name": "Professor of Curvature",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {"path_type": 2},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 30,
                "duration": "this_roll",
            },
            {"type": "cap_floor", "value": 6, "duration": "this_roll"},
        ],
        "tags": ["corner", "velocity"],
    },
    "vel_002": {
        "name": "Technician",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 70,
        "trigger": {"style": "Pace", "path_type": 2},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "cap_floor", "value": 10, "duration": "this_roll"}],
        "tags": ["corner", "pace", "stability"],
    },
    "vel_003": {
        "name": "Lightning Step",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 60,
        "trigger": {
            "phase_min": 2,
            "phase_max": 3,
            "position_group": "back",
            "distance_type": "Medium",
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "modify_gold_range", "value": 50, "duration": "this_turn"},
            {"type": "cap_floor", "value": 6, "duration": "this_roll"},
        ],
        "tags": ["medium", "positioning", "back"],
    },
    "vel_004": {
        "name": "Vanguard Spirit",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {
            "phase_min": 2,
            "phase_max": 3,
            "position_group": "front",
            "distance_type": "Long",
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 5, "duration": "this_roll"},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 40,
                "duration": "this_roll",
            },
        ],
        "tags": ["velocity", "long", "lead"],
    },
    "vel_005": {
        "name": "Killer Tunes",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {
            "distance_type": "Medium",
            "phase_min": 2,
            "phase_max": 3,
            "position_group": "front",
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 3, "duration": "this_roll"},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 40,
                "duration": "this_roll",
            },
        ],
        "tags": ["medium", "lead", "velocity"],
    },
    "vel_006": {
        "name": "Speed Star",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {"style": "Pace", "last_corner": True},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 5, "duration": "this_roll"},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 40,
                "duration": "this_roll",
            },
        ],
        "tags": ["pace", "final_corner", "velocity"],
    },
    "vel_007": {
        "name": "Beeline Burst",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {"path_type": 1},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 3, "duration": "this_roll"},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 40,
                "duration": "this_roll",
            },
        ],
        "tags": ["straight", "velocity"],
    },
    "vel_008": {
        "name": "Flash Forward",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {"path_type": 1, "distance_type": "Medium"},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 5, "duration": "this_roll"},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 40,
                "duration": "this_roll",
            },
        ],
        "tags": ["medium", "straight", "velocity"],
    },
    "vel_009": {
        "name": "Blast Forward",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {"path_type": 1, "distance_type": "Long"},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 5, "duration": "this_roll"},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 40,
                "duration": "this_roll",
            },
        ],
        "tags": ["long", "straight", "velocity"],
    },
    "vel_010": {
        "name": "Sturm und Drang",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {"phase_min": 3, "phase_max": 4, "position_group": "back"},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "modify_velocity", "value": 40, "duration": "this_roll"},
            {"type": "cap_floor", "value": 5, "duration": "this_roll"},
        ],
        "tags": ["late_race", "back", "velocity"],
    },
    "vel_011": {
        "name": "In Body and Mind",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {"lastspurt": True},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "modify_velocity", "value": 40, "duration": "this_roll"},
            {"type": "cap_floor", "value": 5, "duration": "this_roll"},
        ],
        "tags": ["last_spurt", "velocity", "stability"],
    },
    "vel_012": {
        "name": "Rising Dragon",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 70,
        "trigger": {"style": "Late", "phase_min": 3, "phase_max": 4, "path_type": 2},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 7, "duration": "this_roll"},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 30,
                "duration": "this_roll",
            },
        ],
        "tags": ["late", "corner", "burst", "stability"],
    },
    "vel_013": {
        "name": "Tail Nine",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 50,
        "trigger": {"phase_min": 2, "phase_max": 3},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "modify_roll_cap", "value": 10, "duration": "this_roll"}],
        "tags": ["mid_race", "velocity", "cap_boost"],
    },
    "vel_014": {
        "name": "Ramp Up",
        "icon": "velocity",
        "cooldown": 20,
        "cost": 50,
        "trigger": {
            "phase_min": 2,
            "phase_max": 3,
            "target_distance_min": -30,
            "target_distance_max": -1,
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 40,
                "duration": "this_roll",
            }
        ],
        "tags": ["mid_race", "velocity", "positioning"],
    },
    "vel_015": {
        "name": "Uma Stan",
        "icon": "velocity",
        "cooldown": 20,
        "cost": 50,
        "trigger": {"nearby_uma_count": 2},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "modify_roll_cap", "value": 3, "duration": "this_roll"},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 20,
                "duration": "this_roll",
            },
        ],
        "tags": ["velocity"],
    },
    "vel_016": {
        "name": "Homestretch Haste",
        "icon": "velocity",
        "cooldown": 20,
        "cost": 50,
        "trigger": {"last_corner": True},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "modify_roll_cap", "value": 6, "duration": "this_roll"}],
        "tags": ["velocity"],
    },
    "vel_017": {
        "name": "Daring Strike",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {
            "style": "End",
            "phase_min": 2,
            "phase_max": 3,
            "position_group": "back",
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "modify_roll_cap", "value": 5, "duration": "this_roll"},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 40,
                "duration": "this_roll",
            },
        ],
        "tags": ["velocity", "mid_race", "back"],
    },
    "vel_018": {
        "name": "Escape Artist",
        "icon": "Velocity_rare",
        "cooldown": 10,
        "cost": 50,
        "trigger": {"style": "Front", "phase_min": 2, "phase_max": 3},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 40,
                "duration": "this_roll",
            },
            {"type": "modify_roll_cap", "value": 5, "duration": "this_roll"},
            {"type": "reduce_stamina", "value": 1},
        ],
        "tags": ["front", "mid_race", "velocity"],
    },
    "vel_019": {
        "name": "15,000,000 CC",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 70,
        "trigger": {"style": "Late", "path_type": 3},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "cap_floor", "value": 9, "duration": "this_roll"}],
        "tags": ["late", "downhill", "velocity", "stability"],
    },
    "vel_020": {
        "name": "Top Runner",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 60,
        "trigger": {
            "style": "Front",
            "front_blocked": True,
            "phase_min": 1,
            "phase_max": 1,
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 60,
                "duration": "this_roll",
            }
        ],
        "tags": ["front", "start", "blocked", "velocity"],
    },
    "vel_021": {
        "name": "Unstoppable",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {"style": "Pace", "phase_min": 2, "phase_max": 3},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 50,
                "duration": "this_roll",
            },
            {"type": "cap_floor", "value": 3, "duration": "this_roll"},
        ],
        "tags": ["pace", "mid_race", "velocity"],
    },
    "vel_022": {
        "name": "Fast & Furious",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {
            "style": "Late",
            "phase_min": 2,
            "phase_max": 3,
            "position_group": "middle",
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 50,
                "duration": "this_roll",
            },
            {"type": "cap_floor", "value": 3, "duration": "this_roll"},
        ],
        "tags": ["late", "mid_race", "middle", "velocity"],
    },
    "vel_023": {
        "name": "Corner Adept",
        "icon": "velocity",
        "cooldown": 8,
        "cost": 60,
        "trigger": {"path_type": 2},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 10,
                "duration": "this_roll",
            },
            {"type": "cap_floor", "value": 6, "duration": "this_roll"},
        ],
        "tags": ["corner", "velocity"],
    },
    "vel_024": {
        "name": "Straightaway Adept",
        "icon": "velocity",
        "cooldown": 8,
        "cost": 60,
        "trigger": {"path_type": 1},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 3, "duration": "this_roll"},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 20,
                "duration": "this_roll",
            },
        ],
        "tags": ["straightaway", "velocity"],
    },
    "vel_025": {
        "name": "Countermeasure",
        "icon": "velocity",
        "cooldown": 8,
        "cost": 60,
        "trigger": {
            "distance_type": "Sprint",
            "phase_min": 4,
            "phase_max": 4,
            "position_group": "middle",
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 20,
                "duration": "this_roll",
            },
            {"type": "cap_floor", "value": 3, "duration": "this_roll"},
        ],
        "tags": ["sprint", "late_race", "middle", "velocity", "positioning"],
    },
    "vel_026": {
        "name": "Highlander",
        "icon": "velocity",
        "cooldown": 8,
        "cost": 60,
        "trigger": {"path_type": 3},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 6, "duration": "this_roll"},
        ],
        "tags": ["uphill", "velocity"],
    },
    "vel_027": {
        "name": "Playtime's Over!",
        "icon": "velocity",
        "cooldown": 8,
        "cost": 60,
        "trigger": {
            "lastspurt": True,
            "position_group": "front",
            "target_distance_min": -20,
            "target_distance_max": -1,
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 40,
                "duration": "this_roll",
            }
        ],
        "tags": ["front", "lastspurt", "followed", "velocity"],
    },
    "vel_028": {
        "name": "Up-Tempo",
        "icon": "velocity",
        "cooldown": 8,
        "cost": 60,
        "trigger": {
            "distance_type": "Medium",
            "phase_min": 2,
            "phase_max": 3,
            "position_group": "front",
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 3, "duration": "this_roll"},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 25,
                "duration": "this_roll",
            },
        ],
        "tags": ["medium", "front", "mid_race", "velocity", "positioning"],
    },
    "vel_029": {
        "name": "Masterful Gambit",
        "icon": "velocity",
        "cooldown": 8,
        "cost": 60,
        "trigger": {"style": "End", "lastspurt": True, "position_group": "back"},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 3, "duration": "this_roll"},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 25,
                "duration": "this_roll",
            },
        ],
        "tags": ["end", "back", "lastspurt", "velocity"],
    },
    "vel_030": {
        "name": "Prepared to Pass",
        "icon": "velocity",
        "cooldown": 8,
        "cost": 60,
        "trigger": {"style": "Pace", "last_corner": True},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 3, "duration": "this_roll"},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 25,
                "duration": "this_roll",
            },
        ],
        "tags": ["pace", "final_corner", "velocity", "positioning"],
    },
    "vel_031": {
        "name": "Outer Swell",
        "icon": "velocity",
        "cooldown": 8,
        "cost": 60,
        "trigger": {
            "style": "Late",
            "last_corner": True,
            "position_group": "back",
            "target_distance_min": 1,
            "target_distance_max": 150,
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 3, "duration": "this_roll"},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 25,
                "duration": "this_roll",
            },
        ],
        "tags": ["late", "back", "final_corner", "velocity"],
    },
    "vel_032": {
        "name": "Fast-Paced",
        "icon": "velocity",
        "cooldown": 8,
        "cost": 60,
        "trigger": {"style": "Front", "phase_min": 2, "phase_max": 3},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 3, "duration": "this_roll"},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 25,
                "duration": "this_roll",
            },
        ],
        "tags": ["front", "mid_race", "velocity", "positioning"],
    },
    "vel_033": {
        "name": "On the Attack",
        "icon": "velocity",
        "cooldown": 8,
        "cost": 60,
        "trigger": {"style": "Pace", "phase_min": 2, "phase_max": 3},
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 25,
                "duration": "this_roll",
            },
            {"type": "cap_floor", "value": 3, "duration": "this_roll"},
        ],
        "tags": ["pace", "mid_race", "velocity"],
    },
    "vel_034": {
        "name": "1,500,000 CC",
        "icon": "velocity",
        "cooldown": 8,
        "cost": 50,
        "trigger": {"style": "Late", "path_type": 3},
        "target": {"scope": "self", "limit": 1},
        "effects": [{"type": "cap_floor", "value": 6, "duration": "this_roll"}],
        "tags": ["late", "downhill", "velocity", "stability"],
    },
    "vel_035": {
        "name": "Early Start",
        "icon": "velocity",
        "cooldown": 8,
        "cost": 60,
        "trigger": {
            "style": "End",
            "phase_min": 2,
            "phase_max": 3,
            "position_group": "back",
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "modify_roll_cap", "value": 3, "duration": "this_roll"},
            {
                "type": "modify_velocity",
                "mode": "flat_total",
                "value": 25,
                "duration": "this_roll",
            },
        ],
        "tags": ["velocity", "mid_race", "back"],
    },
    "vel_036": {
        "name": "Fearless",
        "icon": "velocity",
        "cooldown": 8,
        "cost": 60,
        "trigger": {
            "style": "Late",
            "phase_min": 3,
            "phase_max": 4,
            "position_group": "middle",
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 4, "duration": "this_roll"},
            {"type": "modify_current_speed", "value": 0.5},
        ],
        "tags": ["late", "middle", "late_race", "acceleration", "stability"],
    },
    "vel_037": {
        "name": "Dauntless",
        "icon": "Velocity_rare",
        "cooldown": 8,
        "cost": 80,
        "trigger": {
            "style": "Late",
            "phase_min": 3,
            "phase_max": 4,
            "position_group": "middle",
        },
        "target": {"scope": "self", "limit": 1},
        "effects": [
            {"type": "cap_floor", "value": 7, "duration": "this_roll"},
            {"type": "modify_current_speed", "value": 1},
        ],
        "tags": ["late", "middle", "late_race", "acceleration", "stability", "rare"],
    },
}
