"""Community-event data kept independently from playable race schedules.

These events are presentation content only.  They never need a RACE_PRESET,
so editing this file cannot change a race track or its gameplay behaviour.
"""

# Dates use 2026 Japanese public holidays or calendar observances where they
# fit the banner theme.  Start times are community-event times in ICT.
EVENT_SCHEDULE: list[dict] = [
    {
        "id": "new-year-2026",
        "kind": "event",
        "name": "New Year Kickoff",
        "description": "นับถอยหลังต้อนรับปีใหม่และเปิดฤดูกาลชุมชน 2026",
        "date": "2026-01-01",
        "time": "00:00",
        "image_url": "/eventBanners/newyear_converted.webp",
    },
    {
        "id": "sweet-valentine-2026",
        "kind": "event",
        "name": "Sweet Valentine Social",
        "description": "กิจกรรมพบปะธีมขนมหวานในวันวาเลนไทน์",
        "date": "2026-02-14",
        "time": "19:00",
        "image_url": "/eventBanners/sweet_converted.webp",
    },
    {
        "id": "white-day-2026",
        "kind": "event",
        "name": "White Day Celebration",
        "description": "กิจกรรมพิเศษสำหรับ White Day",
        "date": "2026-03-14",
        "time": "19:00",
        "image_url": "/eventBanners/WhiteDay_converted.webp",
    },
    {
        "id": "dance-day-2026",
        "kind": "event",
        "name": "Dance Day Showcase",
        "description": "โชว์และกิจกรรมเต้นฉลองวัน International Dance Day",
        "date": "2026-04-29",
        "time": "19:00",
        "image_url": "/eventBanners/dance_converted.webp",
    },
    {
        "id": "greenery-camping-2026",
        "kind": "event",
        "name": "Greenery Day Camp",
        "description": "กิจกรรมแคมป์กลางแจ้งในวัน Greenery Day",
        "date": "2026-05-04",
        "time": "10:00",
        "image_url": "/eventBanners/camping_converted.webp",
    },
    {
        "id": "childrens-day-2026",
        "kind": "event",
        "name": "Children's Day Fun Race",
        "description": "กิจกรรมสนุกสำหรับวันเด็กญี่ปุ่น",
        "date": "2026-05-05",
        "time": "14:00",
        "image_url": "/eventBanners/ChildrensDay_converted.webp",
    },
    {
        "id": "summer-solstice-2026",
        "kind": "event",
        "name": "Summer Solstice Festival",
        "description": "กิจกรรมต้อนรับวันครีษมายันและฤดูร้อน",
        "date": "2026-06-21",
        "time": "18:00",
        "image_url": "/eventBanners/summer_converted.webp",
    },
    {
        "id": "marine-day-water-park-2026",
        "kind": "event",
        "name": "Marine Day Water Park",
        "description": "วันพักผ่อนธีมสวนน้ำในวัน Marine Day",
        "date": "2026-07-20",
        "time": "10:00",
        "image_url": "/eventBanners/waterPark_converted.webp",
    },
    {
        "id": "mountain-day-summer-camp-2026",
        "kind": "event",
        "name": "Mountain Day Summer Camp",
        "description": "แคมป์ฤดูร้อนและกิจกรรมทีมในวัน Mountain Day",
        "date": "2026-08-11",
        "time": "10:00",
        "image_url": "/eventBanners/summercamp_converted.webp",
    },
    {
        "id": "respect-special-2026",
        "kind": "event",
        "name": "Community Special Day",
        "description": "กิจกรรมขอบคุณสมาชิกชุมชนในวัน Respect for the Aged Day",
        "date": "2026-09-21",
        "time": "19:00",
        "image_url": "/eventBanners/specialEvent_converted.webp",
    },
    {
        "id": "sports-power-challenge-2026",
        "kind": "event",
        "name": "Sports Day Power Challenge",
        "description": "กิจกรรมท้าทายพลังและการแข่งขันมินิเกมในวัน Sports Day",
        "date": "2026-10-12",
        "time": "19:00",
        "image_url": "/eventBanners/destructionEvent_converted.webp",
    },
    {
        "id": "halloween-night-2026",
        "kind": "event",
        "name": "Halloween Night Race",
        "description": "คืนพิเศษธีม Halloween พร้อมการแข่งขันและกิจกรรมในชุมชน",
        "date": "2026-10-31",
        "time": "19:00",
        "image_url": "/eventBanners/halloween_converted.webp",
    },
    {
        "id": "culture-day-hollywood-2026",
        "kind": "event",
        "name": "Culture Day Movie Night",
        "description": "Movie night และกิจกรรมธีม Hollywood ในวัน Culture Day",
        "date": "2026-11-03",
        "time": "19:00",
        "image_url": "/eventBanners/hollywood_converted.webp",
    },
    {
        "id": "christmas-festival-2026",
        "kind": "event",
        "name": "Christmas Race Festival",
        "description": "กิจกรรมส่งท้ายปีและการแข่งขันพิเศษธีมคริสต์มาส",
        "date": "2026-12-25",
        "time": "19:00",
        "image_url": "/eventBanners/christmas_converted.webp",
    },
]
